# Generated by Django 5.2.9 on 2026-01-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_categories_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="slug"
            ),
        ),
    ]
