# Generated by Django 5.2.9 on 2026-01-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_products_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="goods/image",
                verbose_name="Фотография",
            ),
        ),
    ]
